### PR TITLE
Remove shared socket functionality

### PR DESCRIPTION
**Pull request by daffl**
This is now in the https://github.com/feathersjs/feathers-socket-commons repository.

### CODE REVIEW

**Comment by ekryski** [comment]
@daffl I'm all for modularity but why did we need to move this to another repo? Genuinely curious, because having things in separate repos does make it a bit trickier to trace and more overhead to manage and feathers-commons was already pretty small.

**Comment by daffl** [comment]
I changed my mind about this a couple of times, too ;) But after implementing the filter functionality, there were a couple of I think good reasons:

1. feathers core does not need any of that code and it was still pulled in
2. feathers-commons started to become a kitchen sink of random stuff that a whole bunch of different modules depend on that don't really have anything to do with each other
3. The socket functionality was only being implicitly tested through the providers so there was basically unused and untested code in the repository mixed up with core shared code.

**Comment by daffl** [comment]
With the event filtering the socket code also became a little more extensive - at least for Feathers standards which justified putting it into its own module especially since it is being shared between `feathers-socketio` and `feathers-primus`.

**Comment by ekryski** [comment]
:+1: sounds good. I forgot that this was part of the event filtering so that makes sense.

**Pull request merged**
